apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "production-master.fullname" . }}-config
  labels:
    {{- include "production-master.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  PORT: {{ .Values.env.PORT | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  LOG_TO_PANORAMA: {{ .Values.env.LOG_TO_PANORAMA | quote }}
  OTEL_SERVICE_NAME: {{ .Values.env.OTEL_SERVICE_NAME | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.env.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
