# Wix staging cluster overrides

replicaCount:
  api: 1
  orchestrator: 1
  worker: 1

env:
  NODE_ENV: staging
  LOG_LEVEL: debug
  LOG_TO_PANORAMA: "true"

hpa:
  enabled: false

postgresql:
  host: staging-postgres.wixpress.com
  port: "5432"
  database: production_master_staging

redis:
  host: staging-redis.wixpress.com
  port: "6379"
