# Wix production cluster overrides

replicaCount:
  api: 3
  orchestrator: 2
  worker: 5

env:
  NODE_ENV: production
  LOG_LEVEL: info
  LOG_TO_PANORAMA: "true"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 15
  targetCPUUtilizationPercentage: 65
  worker:
    minReplicas: 2
    maxReplicas: 15

postgresql:
  host: production-postgres.wixpress.com
  port: "5432"
  database: production_master

redis:
  host: production-redis.wixpress.com
  port: "6379"
